name: "Code Quality"

on:
    pull_request:
        paths:
            - "**.php"
            - "phpcs.xml"
            - ".github/workflows/phpcs.yml"

jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: pdo, pdo_mysql, zip, mysqli, gd

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

#            - name: Install PHP_CodeSniffer
#              run: |
#                  curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
#                  php phpcs.phar --version --config-set ignore_warnings_on_exit 1

            - uses: thenabeel/action-phpcs@v8
              with:
                  files: "**.php"
                  phpcs_path: core/vendor/bin/phpcs
                  standard: phpcs.xml
                  fail_on_warnings: false
